apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-web-app
  labels:
    app: python-web-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-web-app
  template:
    metadata:
      labels:
        app: python-web-app
    spec:
      serviceAccountName: aws-load-balancer-controller 
      containers:
        - name: python-web-app
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}  # Values from values.yaml
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 5
          env:
            - name: RANDOM_COLOR_LAMBDA_URL
              value: {{ .Values.lambda.url }}
      imagePullSecrets:
        - name: ecr-image-pull-secret
