apiVersion: v1
kind: Service
metadata:
  name: python-web-app
  labels:
    app: python-web-app
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80  # Ensure this matches the container port
  selector:
    app: python-web-app
