name: CI/CD

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'


jobs:

  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  build_and_push_docker_image:
    runs-on: ubuntu-latest

    needs: build_and_test

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to AWS ECR
        id: ecr-login
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.ECR_REPOSITORY }}

      - name: build and push docker image to ECR
        env:
          IMAGE_TAG: ${{github.run_id}}
        run:
          docker build -t python-web-app:${IMAGE_TAG} .
          docker tag python-web-app:${IMAGE_TAG} ${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}
          docker push ${{ secrets.ECR_REPOSITORY }}:${IMAGE_TAG}


  update-helm-chart:
    runs-on: ubuntu-latest

    needs: build_and_push_docker_image

    steps: 
      - name: checkout repository
        uses: action/checkout@v4
        with:
          token: ${{ secrets.TOKEN }}

      - name: update tag in helm chart
        run: |
          sed -i 's/tag: .*/tag: "${{github.run_id}}"/' helm/python-web-app-chart/values.yaml

      - name: commit and push the changes
        run: |
          git config --global user.email "ram@gmail.com"
          git config --global user.name "Ramnarendran"
          git add helm/python-web-app-chart/values.yaml
          git commit -m "Update tag in the helm chart to ${{github.run_id}}"
          git push

